/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 public/models/Dog.gltf -o src/components/Dog.jsx -r public
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Dog({hovered, ...props}) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/Dog.gltf')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    const anim = hovered ? "Dance" : "Idle";
    actions[anim].reset().fadeIn(0.5).play();
    return () => actions[anim].fadeOut(0.5);
  }, [hovered])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Body} />
          <primitive object={nodes.Head} />
          <group name="Dog_Blob">
            <skinnedMesh name="Cube015" geometry={nodes.Cube015.geometry} material={materials.Dog_Main} skeleton={nodes.Cube015.skeleton} />
            <skinnedMesh name="Cube015_1" geometry={nodes.Cube015_1.geometry} material={materials.Dog_Secondary} skeleton={nodes.Cube015_1.skeleton} />
            <skinnedMesh name="Cube015_2" geometry={nodes.Cube015_2.geometry} material={materials.Eye_Black} skeleton={nodes.Cube015_2.skeleton} />
            <skinnedMesh name="Cube015_3" geometry={nodes.Cube015_3.geometry} material={materials.Eye_White} skeleton={nodes.Cube015_3.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Dog.gltf')
